// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConnectApiApp.Entities;

public class Sale
{
    public int SaleId { get; set; }

    public int OrderGroupId { get; set; }

    public DateTime PackOutDate { get; set; }

    public int ItemQuantityTotal { get; set; }

    public decimal SubTotal { get; set; }

    public decimal TaxTotal { get; set; }

    public decimal DiscountTotal { get; set; }

    public decimal SaleTotal { get; set; }

    public string PurchaseOrder { get; set; }

    public string Note { get; set; }

    public bool Deleted { get; set; }

    public DateTime CreatedOnUtc { get; set; }

    public string CreatedByImpersonatedUserId { get; set; }

    public string CreatedByWebUserId { get; set; }

    public DateTime? ModifiedOnUtc { get; set; }

    public string ModifiedByWebUserId { get; set; }

    public string ModifiedByImpersonatedUserId { get; set; }

    public DateTime? SentToLightspeed { get; set; }

    public int? MenuId { get; set; }

    public int? ExternalSupplierId { get; set; }

    public string ExternalSaleId { get; set; }

    public DateTime? SaleSentUtc { get; set; }

    public bool LateOrder { get; set; }

    public bool PlacementStarted { get; set; }

    public int? ShoppingCartId { get; set; }

    public int? ReorderOfSaleId { get; set; }

    public int? SaleStatusId { get; set; }

    public string CustomerSaleId { get; set; }
}